# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel

before_install:
  - pip install pip --upgrade;

before_script:
  - R CMD INSTALL .
  - R -e 'reticulate::virtualenv_create("r-reticulate")'
  - R -e 'altair::install_altair("virtualenv")'
  - R -e 'reticulate::py_config()'
  - R -e 'altair::check_altair(quiet = FALSE)'


