# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel

before_script:
  - /usr/bin/python3.4 -m pip install --upgrade --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'reticulate::virtualenv_create("r-reticulate")'
  - R -e 'altair::install_altair("virtualenv")'
  - R -e 'reticulate::py_config()'
  - R -e 'altair::check_altair(quiet = FALSE)'


